import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';

import 'package:arbibot/core/app_export.dart';

/// Main content widget for legal disclaimer
/// Displays comprehensive legal disclaimers and warnings
class DisclaimerContentWidget extends StatelessWidget {
  final VoidCallback onLearnMore;

  const DisclaimerContentWidget({super.key, required this.onLearnMore});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Main Disclaimer Section
        _buildDisclaimerSection(
          context: context,
          title: 'AI-Generated Content Limitations',
          icon: 'info_outline',
          iconColor: theme.colorScheme.primary,
          content: [
            'ArbiBot uses artificial intelligence to assist with legal research and document drafting.',
            'All content generated by ArbiBot is for informational purposes only and does not constitute legal advice.',
            'AI-generated content may contain errors, omissions, or inaccuracies that require professional review.',
          ],
        ),

        SizedBox(height: 2.h),

        // Draft-Only Status Section
        _buildDisclaimerSection(
          context: context,
          title: 'Draft-Only Status Requirements',
          icon: 'draft',
          iconColor: AppTheme.warningLight,
          content: [
            'All documents generated by ArbiBot are drafts only and must be clearly labeled as such.',
            'No document should be filed, submitted, or relied upon without thorough professional review and approval.',
            'You are responsible for verifying all citations, legal arguments, and factual statements.',
          ],
        ),

        SizedBox(height: 2.h),

        // Professional Review Section
        _buildDisclaimerSection(
          context: context,
          title: 'Professional Review Obligations',
          icon: 'verified_user',
          iconColor: theme.colorScheme.secondary,
          content: [
            'As a legal professional, you must conduct independent research and analysis.',
            'You are required to verify all legal citations and ensure they are current and applicable.',
            'Professional judgment must be applied to all AI-generated content before use.',
          ],
        ),

        SizedBox(height: 2.h),

        // Ghana Bar Association Compliance
        _buildDisclaimerSection(
          context: context,
          title: 'Ghana Bar Association Compliance',
          icon: 'gavel',
          iconColor: theme.colorScheme.primary,
          content: [
            'Use of ArbiBot must comply with Ghana Bar Association professional standards.',
            'You remain solely responsible for all legal work product and client communications.',
            'Maintain confidentiality and professional responsibility standards at all times.',
          ],
        ),

        SizedBox(height: 2.h),

        // Confidence Warning System
        _buildConfidenceWarningSection(context),

        SizedBox(height: 2.h),

        // Learn More Link
        InkWell(
          onTap: onLearnMore,
          child: Container(
            padding: EdgeInsets.symmetric(horizontal: 3.w, vertical: 1.5.h),
            decoration: BoxDecoration(
              color: theme.colorScheme.primary.withValues(alpha: 0.05),
              borderRadius: BorderRadius.circular(8.0),
              border: Border.all(
                color: theme.colorScheme.primary.withValues(alpha: 0.2),
                width: 1.0,
              ),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                CustomIconWidget(
                  iconName: 'open_in_new',
                  color: theme.colorScheme.primary,
                  size: 16,
                ),
                SizedBox(width: 2.w),
                Text(
                  'Learn More About Professional Responsibility',
                  style: theme.textTheme.labelLarge?.copyWith(
                    fontSize: 12.sp,
                    color: theme.colorScheme.primary,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  /// Build individual disclaimer section
  Widget _buildDisclaimerSection({
    required BuildContext context,
    required String title,
    required String icon,
    required Color iconColor,
    required List<String> content,
  }) {
    final theme = Theme.of(context);

    return Container(
      padding: EdgeInsets.all(3.w),
      decoration: BoxDecoration(
        color: theme.colorScheme.surface,
        borderRadius: BorderRadius.circular(8.0),
        border: Border.all(color: theme.colorScheme.outline, width: 1.0),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Section Header
          Row(
            children: [
              CustomIconWidget(iconName: icon, color: iconColor, size: 20),
              SizedBox(width: 2.w),
              Expanded(
                child: Text(
                  title,
                  style: theme.textTheme.titleMedium?.copyWith(
                    fontSize: 14.sp,
                    fontWeight: FontWeight.w600,
                    color: theme.colorScheme.onSurface,
                  ),
                ),
              ),
            ],
          ),

          SizedBox(height: 1.5.h),

          // Content Points
          ...content.map(
            (point) => Padding(
              padding: EdgeInsets.only(bottom: 1.h),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Padding(
                    padding: EdgeInsets.only(top: 0.5.h),
                    child: Container(
                      width: 1.5.w,
                      height: 1.5.w,
                      decoration: BoxDecoration(
                        color: theme.colorScheme.onSurfaceVariant,
                        shape: BoxShape.circle,
                      ),
                    ),
                  ),
                  SizedBox(width: 2.w),
                  Expanded(
                    child: Text(
                      point,
                      style: theme.textTheme.bodyMedium?.copyWith(
                        fontSize: 12.sp,
                        color: theme.colorScheme.onSurface,
                        height: 1.5,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// Build confidence warning section
  Widget _buildConfidenceWarningSection(BuildContext context) {
    final theme = Theme.of(context);

    return Container(
      padding: EdgeInsets.all(3.w),
      decoration: BoxDecoration(
        color: AppTheme.warningLight.withValues(alpha: 0.05),
        borderRadius: BorderRadius.circular(8.0),
        border: Border.all(
          color: AppTheme.warningLight.withValues(alpha: 0.3),
          width: 1.5,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Warning Header
          Row(
            children: [
              CustomIconWidget(
                iconName: 'warning',
                color: AppTheme.warningLight,
                size: 20,
              ),
              SizedBox(width: 2.w),
              Expanded(
                child: Text(
                  'Confidence Warning System',
                  style: theme.textTheme.titleMedium?.copyWith(
                    fontSize: 14.sp,
                    fontWeight: FontWeight.w600,
                    color: theme.colorScheme.onSurface,
                  ),
                ),
              ),
            ],
          ),

          SizedBox(height: 1.5.h),

          // Medium Confidence Warning
          _buildConfidenceLevel(
            context: context,
            level: 'Medium Confidence',
            color: AppTheme.warningLight,
            description:
                'Requires additional verification and professional review before use.',
          ),

          SizedBox(height: 1.h),

          // Low Confidence Warning
          _buildConfidenceLevel(
            context: context,
            level: 'Low Confidence',
            color: AppTheme.errorLight,
            description:
                'Requires extensive verification and should not be relied upon without independent research.',
          ),
        ],
      ),
    );
  }

  /// Build confidence level indicator
  Widget _buildConfidenceLevel({
    required BuildContext context,
    required String level,
    required Color color,
    required String description,
  }) {
    final theme = Theme.of(context);

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: 3.w,
          height: 3.w,
          decoration: BoxDecoration(color: color, shape: BoxShape.circle),
        ),
        SizedBox(width: 2.w),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                level,
                style: theme.textTheme.labelLarge?.copyWith(
                  fontSize: 12.sp,
                  fontWeight: FontWeight.w600,
                  color: color,
                ),
              ),
              SizedBox(height: 0.5.h),
              Text(
                description,
                style: theme.textTheme.bodySmall?.copyWith(
                  fontSize: 11.sp,
                  color: theme.colorScheme.onSurface,
                  height: 1.4,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
