from ..models.enums import ConfidenceLevel

SUPPORTED_JURISDICTIONS = {"GH", "GHANA"}

DISCLAIMER_TEXT = (
    "DISCLAIMER: This output is generated by ArbiBot for legal research and drafting "
    "assistance only. It does not constitute legal advice. All outputs should be reviewed "
    "by a qualified legal professional before use. ArbiBot does not guarantee the accuracy "
    "or completeness of any legal information provided."
)


class SafetyAgent:
    """Safety Agent — enforces jurisdiction, confidence gating, and ethical guardrails.

    Runs on every request before any other agent processing.
    """

    def check_jurisdiction(self, jurisdiction: str) -> dict:
        """Verify the request targets a supported jurisdiction."""
        normalized = jurisdiction.upper().strip()
        if normalized not in SUPPORTED_JURISDICTIONS:
            return {
                "allowed": False,
                "reason": f"Jurisdiction '{jurisdiction}' is not supported. ArbiBot currently supports Ghana (GH) only.",
            }
        return {"allowed": True, "jurisdiction": "GH"}

    def check_confidence(self, confidence: ConfidenceLevel) -> dict:
        """Enforce confidence-based gating on outputs."""
        if confidence == ConfidenceLevel.LOW:
            return {
                "allowed": False,
                "reason": "Output confidence is too low to present. The retrieved sources do not provide sufficient basis for a reliable response.",
                "action": "blocked",
            }
        if confidence == ConfidenceLevel.MEDIUM:
            return {
                "allowed": True,
                "warning": "This response has medium confidence. Some sources may not be fully verified. Please review carefully.",
                "action": "warn",
            }
        return {"allowed": True, "action": "pass"}

    def inject_disclaimer(self, response: dict) -> dict:
        """Inject legal disclaimer into any response."""
        response["disclaimer"] = DISCLAIMER_TEXT
        response["is_legal_advice"] = False
        response["requires_human_review"] = True
        return response

    def validate_citations(self, citations: list[dict]) -> dict:
        """Check that citations are not fabricated (stub — full implementation with RAG)."""
        flagged = []
        for citation in citations:
            if not citation.get("source"):
                flagged.append({"citation": citation, "issue": "Missing source name"})
            if citation.get("verified") is True:
                flagged.append({"citation": citation, "issue": "Citation marked as verified without RAG confirmation"})

        return {
            "valid": len(flagged) == 0,
            "flagged_citations": flagged,
            "total_checked": len(citations),
        }

    def run(self, jurisdiction: str, content: dict) -> dict:
        """Run all safety checks on a response."""
        # 1. Jurisdiction check
        jurisdiction_check = self.check_jurisdiction(jurisdiction)
        if not jurisdiction_check["allowed"]:
            return {"blocked": True, "reason": jurisdiction_check["reason"]}

        # 2. Confidence check
        confidence = content.get("confidence", ConfidenceLevel.HIGH)
        if isinstance(confidence, str):
            confidence = ConfidenceLevel(confidence)
        confidence_check = self.check_confidence(confidence)
        if not confidence_check["allowed"]:
            return {"blocked": True, "reason": confidence_check["reason"]}

        # 3. Citation validation
        citations = content.get("citations", [])
        if citations:
            citation_check = self.validate_citations(citations)
            content["citation_validation"] = citation_check

        # 4. Inject disclaimer
        content = self.inject_disclaimer(content)

        # 5. Add warning if medium confidence
        if confidence_check.get("warning"):
            content["confidence_warning"] = confidence_check["warning"]

        return {"blocked": False, "content": content}


def get_safety_agent() -> SafetyAgent:
    return SafetyAgent()
